# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Lista de Tarefas SDM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Lista de Tarefas SDM
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
end
